name: 'discord-notifier'
on:
  issues:
    types: [opened]
  
jobs:
  build:
    name: send discord notification 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#4078c0"
        username: "Github Bot"
        message: "${{ github.event.issue.title }}: ${{ github.event.issue.html_url }}"
