name: Send discord notification
on:
  issues:
    types: [opened]
  
jobs:
  build:
    name: send discord notification 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#48f442"
        username: "${{ github.event.user.login }}"
        avatar_url: "${{ github.event.user.avatar_url }}"
        message: "New issue: ${{ github.event.issue.title }} (${{ github.event.issue.url }})"
        
