name: 'Close issues'

on:
  project_card:
    types: [created, edited, moved]

permissions:
  repository-projects: read
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/issue-states@v2
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          closed-issue-columns: 'Ready for deployment, Live'
